# Generated by Django 2.1.7 on 2019-03-21 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iplcrew', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='question_mom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='Who will man of the match?')),
                ('points', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iplcrew.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iplcrew.iplplayer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qaformmatch.Player')),
            ],
        ),
        migrations.CreateModel(
            name='question_mostboundaries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='Which player will hit most number of boundaries?')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iplcrew.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iplcrew.iplplayer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qaformmatch.Player')),
            ],
        ),
        migrations.CreateModel(
            name='question_mostrun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='Which player will score most runs?')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iplcrew.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iplcrew.iplplayer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qaformmatch.Player')),
            ],
        ),
        migrations.CreateModel(
            name='question_mostsixes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='Which player will hit the most number of sixes?')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iplcrew.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iplcrew.iplplayer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qaformmatch.Player')),
            ],
        ),
        migrations.CreateModel(
            name='question_mostwickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='Which player will take the most wickets?')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iplcrew.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iplcrew.iplplayer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qaformmatch.Player')),
            ],
        ),
        migrations.CreateModel(
            name='question_toss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='Who will win the toss?')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iplcrew.match')),
                ('tosswinner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iplcrew.IPLTeam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qaformmatch.Player')),
            ],
        ),
        migrations.CreateModel(
            name='question_winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default="Select winner team for today's Ipl match.")),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iplcrew.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qaformmatch.Player')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iplcrew.IPLTeam')),
            ],
        ),
    ]
