# Generated by Django 2.1.7 on 2019-03-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qaformmatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
