# Generated by Django 2.1.7 on 2019-03-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplcrew', '0001_initial'),
        ('qaformmatch', '0002_question_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='results',
            name='player_mostboundaries',
        ),
        migrations.AddField(
            model_name='results',
            name='player_mostboundaries',
            field=models.ManyToManyField(null=True, related_name='R_mostboundaries', to='iplcrew.iplplayer'),
        ),
        migrations.RemoveField(
            model_name='results',
            name='player_mostrun',
        ),
        migrations.AddField(
            model_name='results',
            name='player_mostrun',
            field=models.ManyToManyField(null=True, related_name='R_mostrun', to='iplcrew.iplplayer'),
        ),
        migrations.RemoveField(
            model_name='results',
            name='player_mostsixs',
        ),
        migrations.AddField(
            model_name='results',
            name='player_mostsixs',
            field=models.ManyToManyField(null=True, related_name='R_mostsixs', to='iplcrew.iplplayer'),
        ),
        migrations.RemoveField(
            model_name='results',
            name='player_mostwicktect',
        ),
        migrations.AddField(
            model_name='results',
            name='player_mostwicktect',
            field=models.ManyToManyField(null=True, related_name='R_mostwicktect', to='iplcrew.iplplayer'),
        ),
    ]
