# Generated by Django 2.1.7 on 2019-03-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qaformmatch', '0002_results_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='filled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='done',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
