# Generated by Django 2.1.7 on 2019-03-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qaformmatch', '0003_auto_20190329_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='player_mostboundaries',
            field=models.ManyToManyField(related_name='R_mostboundaries', to='iplcrew.iplplayer'),
        ),
        migrations.AlterField(
            model_name='results',
            name='player_mostrun',
            field=models.ManyToManyField(related_name='R_mostrun', to='iplcrew.iplplayer'),
        ),
        migrations.AlterField(
            model_name='results',
            name='player_mostsixs',
            field=models.ManyToManyField(related_name='R_mostsixs', to='iplcrew.iplplayer'),
        ),
        migrations.AlterField(
            model_name='results',
            name='player_mostwicktect',
            field=models.ManyToManyField(related_name='R_mostwicktect', to='iplcrew.iplplayer'),
        ),
    ]
