# Generated by Django 2.1.7 on 2019-03-19 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ipletable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m', models.IntegerField(default=0)),
                ('l', models.IntegerField(default=0)),
                ('nrr', models.FloatField(default=0.0)),
                ('point', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='IPLTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teamname', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField()),
                ('starttime', models.TimeField()),
                ('team_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_1', to='iplcrew.IPLTeam')),
                ('team_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_2', to='iplcrew.IPLTeam')),
            ],
        ),
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('player_type', models.CharField(choices=[('bat', 'Batsman'), ('boll', 'Bowler'), ('wk', 'Wicket keeper'), ('AR', 'All rounder ')], max_length=120)),
                ('Teamname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iplcrew.IPLTeam')),
            ],
        ),
        migrations.AddField(
            model_name='ipletable',
            name='Teamname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iplcrew.IPLTeam'),
        ),
    ]
