# Generated by Django 2.1.7 on 2019-03-22 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ipletable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m', models.IntegerField(default=0)),
                ('l', models.IntegerField(default=0)),
                ('nrr', models.FloatField(default=0.0)),
                ('point', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='iplplayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('player_type', models.CharField(choices=[('bat', 'Batsman'), ('Bwl', 'Bowler'), ('WKB', 'Wicket keeper'), ('All', 'All rounder ')], max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='IPLTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teamname', models.CharField(choices=[('CSK', 'Chennai Super Kings'), ('DC', 'Delhi Capitals'), ('KX1P', 'Kings XI Punjab'), ('KKR', 'Kolkata Knight Riders'), ('RR', 'Rajasthan Royals'), ('MI', 'Mumbai Indians'), ('RBC', 'Royal Challengers Bangalore'), ('SRH', 'Sunrisers Hyderabad\t')], max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='iplplayer',
            name='Teamname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='iplcrew.IPLTeam'),
        ),
        migrations.AddField(
            model_name='ipletable',
            name='Teamname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iplcrew.IPLTeam'),
        ),
    ]
