# Generated by Django 2.1.7 on 2019-03-21 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190321_0414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firs_tname',
            new_name='first_name',
        ),
    ]
